import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ibm } from "./fonts";
import Navbar from "../components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className={`${inter.className} ${ibm.variable} xl:px-[7em] lg:px-[7em] md:px-[6em] sm:px-[4em] px-[2em] py-10`}>
    <Navbar />
    <div className="mt-4">
    {children}
    </div>
   </body>
  </html>
 );
}
