import "@/app/globals.css"
import {AuthProvider} from "../../contexts/auth.context"
import AuthSessionProvider from "../../contexts/providers/auth-session.provider"
import AuthGuard from "@/components/guards/auth-guard";
import {headers} from "next/headers";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function DashboardLayout({
                                            children,
                                        }: {
    children: React.ReactNode
}) {
    const pathname = headers().get('x-pathname');
    return (
        <AuthSessionProvider>
            <AuthProvider>
                <AuthGuard next={pathname}>
                    <>
                        {children}
                    </>
                </AuthGuard>
            </AuthProvider>
        </AuthSessionProvider>
    )
}
