import "@/app/globals.css"
import { AuthProvider } from "../../contexts/auth.context"
import AuthSessionProvider from "../../contexts/auth-session.provider"
export const metadata = {
 title: 'Next.js',
 description: 'Generated by Next.js',
}

export default function RootLayout({
 children,
}: {
 children: React.ReactNode
}) {
 return (
  <html lang="en">
   <body>
    <AuthSessionProvider>
     <AuthProvider>
      {children}
     </AuthProvider>
    </AuthSessionProvider>
   </body>
  </html>
 )
}
